### ISSUE TITLE
[Feature Request] Automatic mapping from "kid to Transit Key"

### ISSUE THREAD

**Issue by in0rdr** [p15r/distributey#100]
Automatic mapping from "kid to Vault Transit Key" according to some predefined scheme/rule.

Currently, the mapping is done statically in the `backend` section of the configuration file ([`config/config.json`](https://github.com/p15r/distributey/blob/main/config/config.json)).

Can this mapping be written in Python code, so that we have the business logic (mapping rule), which Key from Vault is returned in response to a request with a specific `kid` (Key ID) in the code?

Strengths of this Feature/Idea:
- Less configuration effort (Operator only configures Vault keys and Distributey automatically fetches the correct key)
- Business logic over configuration logic
- It might be faster to add additional keys for a consumer/service (only changes in Vault required)

Weaknesses of this Feature/Idea:
- Less flexible. The Vault Key is implicitly defined through the `kid` in the request.
- Might require additional space in the cache to store a mapping (`kid` to Vault Tenant Key) for repeated requests?

**Comment by p15r** [comment]
Hi @in0rdr 
I thought this might be handy, this is why I implemented: https://github.com/p15r/distributey/blob/9ac8565970cf84ac45ceaf58b0051e1bf6d41871/distributey/app.py#L321
If you have a look at this view lines of code, distributey tries to fetch a mapping between `jwe kid` and `vault key path`. If that mapping does not exist, I simply assume that `jwe kid` equals to the `vault key path`.

Does that address your problem? You can try this by simply not configuring a `vault key path`: https://github.com/p15r/distributey/blob/f1d00a7e8690cd42c64c92d087c9d70e8e91dca0/config/config.json#L25

**Comment by p15r** [comment]
I realized that the current solution does autom. mapping `jwe kid -> vault key path`. However, it still requires configuration of  a key consumer certificate per `jwe kid`. I changes this in PR https://github.com/p15r/distributey/pull/104. This PR allows creating one key consumer cert per tenant.
@in0rdr can you test the PR and confirm this addresses your needs?

**Comment by in0rdr** [comment]
This should address our needs, thank you.

**Comment by p15r** [comment]
Nice 👍 One feature down, one to go 🤘
