### ISSUE TITLE
Vault Namespace

### ISSUE THREAD

**Issue by in0rdr** [p15r/distributey#98]
Can we retrieve the Transit key from a Vault Namespace?

```
client = hvac.Client(
    url='https://localhost:8200',
    namespace=os.getenv('VAULT_NAMESPACE'),
)
```
https://hvac.readthedocs.io/en/stable/overview.html

https://github.com/p15r/distributey/blob/main/distributey/vault_backend.py#L49

**Comment by in0rdr** [comment]
Can we move Authentication to the namespace level?

**Comment by p15r** [comment]
Sure, see my comment on the PR https://github.com/p15r/distributey/pull/99

**Comment by p15r** [comment]
Finally merged! 🎉 🎉 
Many thanks for all the support! 🤘
